### ISSUE TITLE
MCP4017 values are incorrectly written/read

### ISSUE THREAD

**Issue by se-bastiaan** [se-bastiaan/esphome-simplebus2#1]
```
[C][simplebus2:027]: Setting up Simplebus2
[D][simplebus2:348]: Gain to set: 30
[D][simplebus2:355]: Gain resistor value: 3448.275879
[D][simplebus2:311]: Write value of MCP4017 0: 4
[D][simplebus2:362]: Voltage to set: 200
[D][simplebus2:368]: Voltage limit resistor value: 6451.612793
[D][simplebus2:311]: Write value of MCP4017 1: 8
[D][simplebus2:342]: Current resistance of MCP4017 0: 8
[D][simplebus2:342]: Current resistance of MCP4017 1: 8
[D][binary_sensor:036]: 'Incoming call': Sending state OFF
[C][simplebus2:055]: Setup for Simplebus2 complete
```

Not entirely sure yet what is going on here but the resistance for the two MCP4017 chips should not be the same.
Turning around the two writing operations does result in the latest value written however.

**Comment by Elektroarzt** [comment]
Maybe it helps ... gurkenflieger wrote the Arduino code for the original project and also faced the issue of not working voltage dividers. He then sent some initial reset commands to the potentiometers and voila, everything worked fine. I made a measurement series about accuracy of the threshold with the fix and it was quite good:
<img width="373" alt="image" src="https://github.com/se-bastiaan/esphome-simplebus2/assets/61664171/a39457ec-9935-4759-9d57-30fb57f30b30">

**Comment by Elektroarzt** [comment]
For the gain I also successfully measured a complete series after the fix. CH1 is before the comparator U6 and CH2 is after the comparator. Here just a few gain values ... If you need more, let me know.

<img width="400" alt="image" src="https://github.com/se-bastiaan/esphome-simplebus2/assets/61664171/a3e0330f-da43-4155-96be-b1e64dfda8f8">
<img width="400" alt="image" src="https://github.com/se-bastiaan/esphome-simplebus2/assets/61664171/17804850-46dc-49a5-a99c-54fde5b6155c">
<img width="400" alt="image" src="https://github.com/se-bastiaan/esphome-simplebus2/assets/61664171/732121d9-0045-45e5-b808-89fe8e23f575">

**Comment by se-bastiaan** [comment]
thanks! maybe i should try some repeated resets when I have time

it's certainly weird, before i reflashed Saturday morning everything worked fine for two weeks or so. Now I don't see anything coming in at all

**Comment by se-bastiaan** [comment]
Seems like the problem is the reading, same happens with the original firmware. And I've got the events working so 🤷 
![Scherm­afbeelding 2024-04-24 om 19 30 46](https://github.com/se-bastiaan/esphome-simplebus2/assets/1799914/84490370-cfe8-4a8d-b6c8-85dcac901fef)
